# Generated by Django 4.2 on 2023-06-07 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='token',
        ),
    ]
