# Generated by Django 4.2.1 on 2023-06-08 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_session_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
    ]
