# Generated by Django 4.2 on 2023-06-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='view_graph',
            field=models.BooleanField(default=True),
        ),
    ]
