# Generated by Django 4.2 on 2023-06-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_alter_sensorsusers_sensor_alter_sensorsusers_user'),
        ('users', '0014_user_name_user_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_sensor',
            field=models.ManyToManyField(to='sensors.sensor'),
        ),
    ]
