# Generated by Django 4.2 on 2023-07-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_user_is_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='view_plan',
            field=models.BooleanField(default=True),
        ),
    ]
