# Generated by Django 4.2 on 2023-06-04 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pollutants', '0001_initial'),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('success', models.BooleanField(blank=True, default=False, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.city')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pollutant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollutants.pollutant')),
                ('current_quantity', models.FloatField(),),
                ('goal_threshold', models.FloatField(),),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.plan')),
            ],
        ),
    ]
