# Generated by Django 4.2 on 2023-06-04 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='model',
        ),
    ]
