# Generated by Django 4.2.1 on 2023-06-08 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_session_token'),
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorsUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sensors.sensor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.user')),
            ],
        ),
    ]
