# Generated by Django 4.2 on 2023-05-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='date_change_filter',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='oxidation_level',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
