# Generated by Django 4.2 on 2023-06-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_remove_sensor_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='sensor_model',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
