# Generated by Django 4.2 on 2023-06-05 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_alter_rilevation_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rilevation',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sensors.sensor'),
        ),
    ]
