# Generated by Django 4.2 on 2023-06-07 21:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pollutants', '0001_initial'),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
                ('mortality_index', models.IntegerField(blank=True, null=True)),
                ('average_duration_days', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_code', models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(16)])),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('gender', models.TextField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('population', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.city')),
            ],
        ),
        migrations.CreateModel(
            name='SickIllness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilness.illness')),
                ('sick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilness.sick')),
            ],
        ),
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilness.illness')),
                ('pollution_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollutants.pollutiontype')),
            ],
        ),
    ]
