# Generated by Django 3.2.18 on 2023-05-28 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('pollutants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.city')),
            ],
        ),
        migrations.CreateModel(
            name='SickIllness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilness.illness')),
                ('sick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilness.sick')),
            ],
        ),
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilness.illness')),
                ('pollution_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollutants.pollutiontype')),
            ],
        ),
    ]
