# Generated by Django 4.2 on 2023-05-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illness',
            name='nome',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
