# Generated by Django 4.2 on 2023-06-04 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilness', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='illness',
            name='average_duration_days',
        ),
        migrations.RemoveField(
            model_name='illness',
            name='mortality_index',
        ),
    ]
