# Generated by Django 4.2 on 2023-06-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilness', '0002_remove_illness_average_duration_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='illness',
            name='average_duration_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='illness',
            name='mortality_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
