# Generated by Django 4.2 on 2023-05-28 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20230528_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='inhabitants_name',
        ),
        migrations.AlterField(
            model_name='city',
            name='female_percentage',
            field=models.PositiveIntegerField(blank=True, default=10, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='city',
            name='inhabitants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='male_percentage',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
