# Generated by Django 3.2.18 on 2023-05-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollutants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollutant',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='pollutiontype',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
