# Generated by Django 4.2 on 2023-06-05 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pollutants', '0002_alter_pollutant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollutant',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollutants.pollutiontype'),
        ),
    ]
